[tool.poetry]
name = "python-service"
version = "0.0.1"
description = ""
authors = ["Steven Vo <tvo-c@wisq.com>"]

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[tool.poetry.dependencies]
fastapi = "^0.112.0"