[tool.poetry]
name = "python-service"
version = "0.0.6"
description = ""
authors = ["Steven Vo <tvo-c@wisq.com>"]
package-mode = false

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.103.0"