# .github/workflows/ci.yml
name: Python CI

on:
  push:
    branches: [ main, hotfix/* ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: get project info
        run: |
          echo "PROJECT_NAME=$(cat ./pyproject.toml | grep -m 1 "name = " | head -1 | tr -d '"' | awk '{print $3}')" >> $GITHUB_ENV
          echo "PROJECT_VERSION=$(cat ./pyproject.toml | grep -m 1 "version = " | tr -d '"' | awk '{print $3}')" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # generate OpenAPI documentation
      - name: python doc
        run: |
          poetry run python3 -m generate_doc

      - name: generate doc
        run: |
          ls -l
          npm install -g @redocly/cli@latest
          redocly build-docs openapi.json -o apidoc/docs-${{ env.PROJECT_VERSION }}.html
          cp openapi.json apidoc/docs-${{ env.PROJECT_VERSION }}.json

      # upload HTML doc as build artifact
      - name: Upload doc
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT_NAME }}-${{ env.PROJECT_VERSION }}.html
          path: apidoc

      - name: tag
        continue-on-error: false
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          tag: ${{ env.PROJECT_VERSION }}
        if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/hotfix') ) }}

      - name: publish docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: apidoc
          target-folder: ${{env.PUB_DIR}}
          clean: false
